<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="SSH.NET" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Agw.Shared\Agw.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Abstracts\" />
    </ItemGroup>

</Project>
