<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Agents.AI" />
    <ProjectReference Include="..\Agw.Agents.Contracts\Agw.Agents.Contracts.csproj" />
    <ProjectReference Include="..\Agw.Shared\Agw.Shared.csproj" />
  </ItemGroup>
</Project>
