<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <ProjectReference Include="..\DSystem.Shared.Contract\DSystem.Shared.Contract.csproj" />
    <ProjectReference Include="..\DSystem.Shared\DSystem.Shared.csproj" />
  </ItemGroup>
</Project>
