<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agw.Auth\Agw.Auth.csproj" />
    <ProjectReference Include="..\Agw.Infrastructure\Agw.Infrastructure.csproj" />
    <ProjectReference Include="..\Agw.Shared\Agw.Shared.csproj" />
    <ProjectReference Include="..\Agw.Skills\Agw.Skills.csproj" />
  </ItemGroup>
</Project>
