import { StyleSheet } from "react-native";
import { colors } from "./tokens";

export const styles = StyleSheet.create({
  root: {
    alignItems: "center",
    backgroundColor: colors.background,
    flex: 1,
  },
  phoneFrame: {
    backgroundColor: colors.background,
    flex: 1,
    maxWidth: 430,
    width: "100%",
  },
  topBar: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
  },
  segmentedTabs: {
    backgroundColor: colors.segment,
    borderRadius: 8,
    flexDirection: "row",
    height: 34,
    padding: 4,
    width: 165,
  },
  segmentTab: {
    alignItems: "center",
    borderRadius: 6,
    flex: 1,
    justifyContent: "center",
    minWidth: 0,
  },
  segmentTabActive: {
    backgroundColor: colors.primary,
    shadowColor: "#000000",
    shadowOffset: { height: 1, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 1,
  },
  segmentText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0,
    lineHeight: 18,
  },
  segmentTextActive: {
    color: colors.white,
    fontWeight: "700",
  },
  headerActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "flex-end",
    minWidth: 72,
  },
  mainPanel: {
    backgroundColor: colors.white,
    borderLeftColor: colors.border,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderRightColor: colors.border,
    borderRightWidth: StyleSheet.hairlineWidth,
    flex: 1,
    overflow: "hidden",
  },
  panelScroll: {
    flex: 1,
    paddingHorizontal: 16
  },
  emptyPanel: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  emptyPanelText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.3,
    lineHeight: 20,
    textAlign: "center",
  },
  errorText: {
    color: colors.red,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 20,
    textAlign: "center",
  },
  chatContent: {
    gap: 12,
    paddingBottom: 32,
    paddingTop: 1,
  },
  dateDivider: {
    alignSelf: "center",
    backgroundColor: colors.datePill,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 4,
  },
  dateDividerText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
    lineHeight: 14,
  },
  selfMessageRow: {
    alignItems: "flex-end",
    paddingLeft: 80,
  },
  selfBubble: {
    backgroundColor: colors.primary,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 4,
    borderColor: colors.primaryBorder,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    maxWidth: 298,
    paddingHorizontal: 17,
    paddingVertical: 17,
  },
  selfBubbleText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 22,
  },
  bubbleShadow: {
    elevation: 1,
    shadowColor: "#000000",
    shadowOffset: { height: 1, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 1,
  },
  receiverGroup: {
    alignItems: "flex-start",
    marginLeft: 0,
  },
  receiverGroupCompact: {
    alignItems: "flex-start",
    marginLeft: 44,
    marginTop: 16,
    maxWidth: 254,
  },
  senderLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 14,
    marginBottom: 4,
    marginLeft: 8,
  },
  receiverBubble: {
    backgroundColor: colors.received,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 16,
    borderColor: colors.receivedBorder,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 17,
    width: "100%",
  },
  receiverBubbleCompact: {
    maxWidth: 254,
  },
  receiverBubbleText: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 22,
  },
  messageTitle: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 14,
    marginBottom: 6,
  },
  selfMessageTitle: {
    color: colors.white,
    opacity: 0.78,
    textAlign: "right",
  },
  messageContentContainer: {
    gap: 8,
  },
  messageContent: {
    minWidth: 0,
    fontSize: 16,
    lineHeight: 22,
  },
  markdownBody: {
    fontSize: 15,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 22,
  },
  receiverMarkdownBody: {
    color: colors.ink,
  },
  selfMarkdownBody: {
    color: colors.white,
  },
  reasoningMarkdownBody: {
    color: colors.muted,
  },
  markdownParagraph: {
    marginBottom: 8,
    marginTop: 0,
  },
  markdownStrong: {
    fontWeight: "700",
  },
  markdownList: {
    marginBottom: 8,
    marginTop: 2,
  },
  markdownListItem: {
    marginBottom: 4,
  },
  markdownCodeInline: {
    backgroundColor: "#fdf6e3",
    borderColor: colors.border,
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    color: colors.ink,
    fontSize: 13,
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  selfMarkdownCodeInline: {
    backgroundColor: "#fdf6e3",
    borderColor: colors.border,
    color: colors.ink,
  },
  markdownCodeBlock: {
    backgroundColor: "#fdf6e4",
    borderColor: colors.border,
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    color: colors.ink,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 0,
    marginTop: 2,
    padding: 10,
  },
  selfMarkdownCodeBlock: {
    backgroundColor: "#fdf6e4",
    borderColor: colors.border,
    color: colors.ink,
  },
  toolGroup: {
    alignSelf: "stretch",
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    gap: 10,
    marginHorizontal: 24,
    padding: 10,
  },
  toolGroupHeader: {
    borderBottomColor: colors.borderSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 2,
    paddingBottom: 8,
  },
  toolGroupEyebrow: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 14,
  },
  toolGroupTitle: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 18,
  },
  toolGroupMessages: {
    gap: 10,
  },
  typingIndicator: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    justifyContent: "center",
    opacity: 0.7,
    paddingTop: 1,
  },
  typingText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 14,
  },
  typingDots: {
    flexDirection: "row",
    gap: 2,
  },
  typingDot: {
    backgroundColor: colors.muted,
    borderRadius: 999,
    height: 4,
    width: 4,
  },
  filesContent: {
    paddingBottom: 32,
  },
  filesWorkspace: {
    backgroundColor: colors.white,
    flex: 1,
  },
  explorerPanel: {
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flex: 1,
    minHeight: 0,
  },
  accordionCollapsedPanel: {
    flex: 0,
    minHeight: 0,
  },
  accordionHeader: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: 8,
    minHeight: 54,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  accordionTitleColumn: {
    flex: 1,
    minWidth: 0,
  },
  explorerHeader: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: 10,
    minHeight: 64,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  explorerTitleColumn: {
    flex: 1,
    minWidth: 0,
  },
  explorerTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 18,
  },
  explorerPath: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0,
    lineHeight: 15,
    marginTop: 2,
  },
  explorerActions: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: 6,
    justifyContent: "flex-end",
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  diffSwitchRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
  },
  diffSwitchLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 16,
  },
  refreshButton: {
    alignItems: "center",
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    justifyContent: "center",
    minHeight: 34,
    minWidth: 72,
    paddingHorizontal: 10,
  },
  refreshButtonDisabled: {
    opacity: 0.6,
  },
  refreshButtonText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 16,
  },
  filesTreeScroll: {
    flex: 1,
  },
  filesTreeContent: {
    paddingBottom: 16,
  },
  filesStateBlock: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  fileLeafSpacer: {
    width: 16,
  },
  fileRowSelected: {
    backgroundColor: colors.surface,
  },
  deletedFileTitle: {
    color: colors.muted,
    textDecorationLine: "line-through",
  },
  gitStatusBadge: {
    alignItems: "center",
    borderRadius: 4,
    justifyContent: "center",
    marginLeft: 6,
    minWidth: 22,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  gitStatusAdded: {
    backgroundColor: "#dcfce7",
  },
  gitStatusModified: {
    backgroundColor: "#fef3c7",
  },
  gitStatusDeleted: {
    backgroundColor: "#fee2e2",
  },
  gitStatusUntracked: {
    backgroundColor: "#dbeafe",
  },
  gitStatusText: {
    color: colors.ink,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0,
    lineHeight: 12,
  },
  fileStatusBanner: {
    backgroundColor: colors.surface,
    borderBottomColor: colors.borderSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  fileStatusText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 16,
  },
  fileContentPanel: {
    backgroundColor: colors.white,
    flex: 1,
    minHeight: 0,
  },
  fileContentEmpty: {
    alignItems: "center",
    backgroundColor: colors.white,
    flex: 1,
    gap: 10,
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  fileContentHeader: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: 8,
    minHeight: 54,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  fileContentHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  fileContentTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 18,
  },
  fileContentPath: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0,
    lineHeight: 14,
    marginTop: 1,
  },
  fileContentState: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  fileViewerScroll: {
    flex: 1,
  },
  diffSection: {
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  diffSectionTitle: {
    borderBottomColor: colors.borderSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0,
    lineHeight: 18,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  diffOriginalTitle: {
    backgroundColor: "#fef2f2",
    color: "#7f1d1d",
  },
  diffModifiedTitle: {
    backgroundColor: "#f0fdf4",
    color: "#14532d",
  },
  unchangedBanner: {
    backgroundColor: colors.surface,
    borderColor: colors.borderSoft,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    margin: 12,
    padding: 10,
  },
  unchangedBannerText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 18,
  },
  codeViewer: {
    paddingVertical: 6,
  },
  codeLine: {
    alignItems: "flex-start",
    flexDirection: "row",
    minHeight: 28,
  },
  codeLineActive: {
    backgroundColor: colors.surface,
  },
  codeLineNumber: {
    borderRightColor: colors.borderSoft,
    borderRightWidth: StyleSheet.hairlineWidth,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 20,
    minWidth: 42,
    paddingHorizontal: 8,
    paddingVertical: 4,
    textAlign: "right",
  },
  codeLineText: {
    color: colors.ink,
    fontFamily: "monospace",
    fontSize: 12,
    lineHeight: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  commentSection: {
    backgroundColor: colors.surface,
    borderLeftColor: colors.primary,
    borderLeftWidth: 3,
    borderTopColor: colors.borderSoft,
    borderTopWidth: StyleSheet.hairlineWidth,
    marginLeft: 42,
    padding: 8,
  },
  commentItem: {
    alignItems: "flex-start",
    borderBottomColor: colors.borderSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: 8,
    paddingBottom: 8,
  },
  commentTextColumn: {
    flex: 1,
    minWidth: 0,
  },
  commentTimestamp: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 13,
    marginBottom: 3,
  },
  commentText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "500",
    letterSpacing: 0,
    lineHeight: 18,
  },
  commentDeleteButton: {
    backgroundColor: "#fee2e2",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  commentDeleteButtonText: {
    color: colors.red,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0,
    lineHeight: 14,
  },
  commentInputGroup: {
    gap: 8,
    paddingTop: 8,
  },
  commentInput: {
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    color: colors.ink,
    fontSize: 13,
    minHeight: 76,
    paddingHorizontal: 10,
    paddingVertical: 8,
    textAlignVertical: "top",
  },
  commentActionRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "flex-end",
  },
  commentSaveButton: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: 7,
    minHeight: 34,
    minWidth: 72,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  commentSaveButtonText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0,
    lineHeight: 16,
  },
  commentCancelButton: {
    alignItems: "center",
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 7,
    borderWidth: StyleSheet.hairlineWidth,
    minHeight: 34,
    minWidth: 72,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  commentCancelButtonText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0,
    lineHeight: 16,
  },
  fileActionSheet: {
    backgroundColor: colors.white,
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    bottom: 0,
    gap: 10,
    left: 0,
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: "absolute",
    right: 0,
  },
  fileActionTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0,
    lineHeight: 18,
  },
  fileActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  fileActionButton: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    minHeight: 38,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  fileActionButtonText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0,
    lineHeight: 17,
  },
  fileActionButtonDanger: {
    alignItems: "center",
    backgroundColor: "#fee2e2",
    borderColor: "#fecaca",
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    minHeight: 38,
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  fileActionButtonDangerText: {
    color: colors.red,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0,
    lineHeight: 17,
  },
  folderRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    minHeight: 49,
    paddingRight: 16,
  },
  fileRowTopBorder: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  folderTitle: {
    color: colors.ink,
    flex: 1,
    fontSize: 16,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 22,
    minWidth: 0,
  },
  folderTitleBold: {
    fontWeight: "700",
  },
  infoIconSlot: {
    marginLeft: "auto",
  },
  fileRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    minHeight: 58,
    paddingRight: 16,
  },
  nestedFileRowTopBorder: {
    borderTopColor: colors.borderSoft,
    borderTopWidth: StyleSheet.hairlineWidth,
    marginLeft: 32,
  },
  fileTextColumn: {
    flex: 1,
    minWidth: 0,
  },
  fileTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 18,
  },
  fileMeta: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 12,
  },
  composer: {
    backgroundColor: colors.surface,
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    gap: 8,
    paddingHorizontal: 20,
    paddingTop: 17,
  },
  toolbarRow: {
    alignItems: "center",
    flexDirection: "row",
    height: 36,
    justifyContent: "space-between",
  },
  toolbarGroup: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  inputRow: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 16,
  },
  inputShell: {
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    height: 58,
    justifyContent: "center",
    paddingHorizontal: 29,
  },
  messageInput: {
    color: colors.ink,
    fontSize: 15,
    height: 42,
    letterSpacing: 0,
    lineHeight: 20,
    padding: 0,
  },
  sendButton: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: 12,
    height: 48,
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    width: 48,
  },
  sendButtonDisabled: {
    opacity: 0.45,
  },
  drawerLayer: {
    backgroundColor: colors.background,
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 20,
  },
  drawerPanel: {
    backgroundColor: colors.white,
    borderRightColor: colors.border,
    borderRightWidth: StyleSheet.hairlineWidth,
    flex: 1,
    width: "100%",
  },
  drawerHeader: {
    alignItems: "center",
    backgroundColor: colors.background,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
  },
  drawerBrand: {
    color: colors.primary,
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 28,
  },
  drawerTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    minWidth: 0,
  },
  drawerTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 24,
  },
  drawerSelectors: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  drawerSelectColumn: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  selectLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 15,
  },
  selectBox: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    height: 28,
    justifyContent: "space-between",
    paddingLeft: 9,
    paddingRight: 7,
  },
  selectBoxActive: {
    borderColor: colors.primary,
  },
  selectValue: {
    color: colors.ink,
    flex: 1,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 14,
    minWidth: 0,
  },
  drawerOptions: {
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 4,
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 8,
  },
  selectorOption: {
    borderRadius: 8,
    minHeight: 38,
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  selectorOptionText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 18,
  },
  selectorOptionMeta: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
    lineHeight: 13,
  },
  historySection: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
  },
  sectionLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 15,
    marginBottom: 14,
  },
  historyItem: {
    borderRadius: 12,
    paddingHorizontal: 4,
    paddingVertical: 12,
  },
  historyItemActive: {
    backgroundColor: colors.surface,
  },
  historyItemPressed: {
    backgroundColor: colors.surface,
  },
  historyTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 24,
  },
  historyPreview: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 14,
  },
  drawerFooter: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 16,
    paddingTop: 9,
  },
  settingsRow: {
    alignItems: "center",
    borderRadius: 999,
    flexDirection: "row",
    gap: 12,
    minHeight: 48,
    paddingHorizontal: 16,
  },
  settingsText: {
    color: colors.muted,
    fontSize: 16,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 24,
  },
  settingsPage: {
    backgroundColor: colors.white,
    flex: 1,
    gap: 16,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  configOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(250, 249, 254, 0.98)",
    bottom: 0,
    justifyContent: "center",
    left: 0,
    paddingHorizontal: 18,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 30,
  },
  configSheet: {
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    gap: 14,
    maxWidth: 390,
    padding: 20,
    shadowColor: "#000000",
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    width: "100%",
  },
  configEyebrow: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 15,
  },
  configTitle: {
    color: colors.ink,
    fontSize: 22,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 28,
  },
  configDescription: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 20,
  },
  configTextArea: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    color: colors.ink,
    fontSize: 14,
    height: 150,
    letterSpacing: 0,
    lineHeight: 19,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  configError: {
    color: colors.red,
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0,
    lineHeight: 18,
  },
  configActionRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "flex-end",
  },
  settingsActionRow: {
    marginTop: "auto",
  },
  configPrimaryButton: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: 8,
    minHeight: 44,
    minWidth: 104,
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  configPrimaryButtonText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 20,
  },
  configSecondaryButton: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    minHeight: 44,
    minWidth: 96,
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  configSecondaryButtonText: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 20,
  },
  settingsHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  settingsTitleColumn: {
    flex: 1,
    gap: 4,
    minWidth: 0,
    paddingRight: 16,
  },
  settingsFields: {
    gap: 12,
  },
  settingsField: {
    gap: 6,
  },
  settingsFieldLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  settingsTextInput: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    color: colors.ink,
    fontSize: 15,
    height: 46,
    letterSpacing: 0,
    lineHeight: 20,
    paddingHorizontal: 12,
  },
  loadingPanel: {
    alignItems: "center",
    backgroundColor: colors.background,
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  loadingText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 20,
  },
  iconButton: {
    alignItems: "center",
    borderRadius: 999,
    justifyContent: "center",
  },
  pressed: {
    opacity: 0.7,
  },
  iconCanvas: {
    position: "relative",
  },
  iconCenter: {
    alignItems: "center",
    justifyContent: "center",
  },
  iconLine: {
    borderRadius: 999,
    position: "absolute",
  },
  moreDot: {
    borderRadius: 999,
    position: "absolute",
  },
  folderTab: {
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    position: "absolute",
  },
  folderBody: {
    borderRadius: 2,
    position: "absolute",
  },
  infoIcon: {
    alignItems: "center",
    borderRadius: 999,
    borderWidth: 1.5,
    justifyContent: "center",
  },
  infoIconText: {
    fontWeight: "700",
    includeFontPadding: false,
    lineHeight: 16,
  },
  toolbarImageIcon: {
    borderRadius: 1,
    borderWidth: 1.8,
    position: "relative",
  },
  toolbarImageSun: {
    borderRadius: 999,
    height: 3,
    left: 4,
    position: "absolute",
    top: 4,
    width: 3,
  },
  toolbarImageMountain: {
    borderBottomWidth: 7,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    bottom: 3,
    height: 0,
    position: "absolute",
    right: 3,
    width: 0,
  },
  paperclipOuter: {
    borderRadius: 999,
    borderWidth: 2,
    transform: [{ rotate: "8deg" }],
  },
  paperclipInner: {
    borderRadius: 999,
    borderWidth: 1.6,
    bottom: 3,
    left: 3,
    position: "absolute",
    right: 3,
    top: 5,
  },
  smileFace: {
    borderRadius: 999,
    borderWidth: 1.8,
    position: "relative",
  },
  smileEye: {
    borderRadius: 999,
    height: 3,
    position: "absolute",
    top: 7,
    width: 3,
  },
  smileMouth: {
    borderBottomWidth: 1.8,
    borderRadius: 999,
    bottom: 6,
    height: 5,
    left: 6,
    position: "absolute",
    right: 6,
  },
  micCapsule: {
    borderRadius: 999,
    borderWidth: 1.8,
    position: "absolute",
  },
  micStem: {
    borderRadius: 999,
    position: "absolute",
  },
  micBase: {
    borderRadius: 999,
    position: "absolute",
  },
  circlePlus: {
    alignItems: "center",
    borderRadius: 999,
    borderWidth: 1.8,
    justifyContent: "center",
  },
  fileImageIcon: {
    backgroundColor: colors.purple,
    borderRadius: 2,
    position: "relative",
  },
  fileImageDot: {
    backgroundColor: colors.white,
    borderRadius: 999,
    height: 3,
    left: 3,
    position: "absolute",
    top: 3,
    width: 3,
  },
  fileImageHill: {
    borderBottomColor: colors.white,
    borderBottomWidth: 6,
    borderLeftColor: "transparent",
    borderLeftWidth: 5,
    borderRightColor: "transparent",
    borderRightWidth: 5,
    bottom: 3,
    height: 0,
    position: "absolute",
    right: 2,
    width: 0,
  },
  filePdfIcon: {
    backgroundColor: colors.red,
    borderRadius: 2,
    position: "relative",
  },
  fileFold: {
    borderLeftColor: "transparent",
    borderLeftWidth: 5,
    borderTopColor: colors.white,
    borderTopWidth: 5,
    height: 0,
    position: "absolute",
    right: 0,
    top: 0,
    width: 0,
  },
  filePdfLine: {
    backgroundColor: colors.white,
    borderRadius: 999,
    height: 2,
    left: 3,
    position: "absolute",
    right: 3,
    top: 9,
  },
  filePdfLineShort: {
    right: 7,
    top: 13,
  },
  fileSheetIcon: {
    borderRadius: 2,
    overflow: "hidden",
  },
  fileSheetHeader: {
    backgroundColor: colors.brown,
    height: 5,
  },
  sheetCells: {
    backgroundColor: colors.brown,
    flex: 1,
    flexDirection: "row",
    gap: 2,
    paddingHorizontal: 2,
    paddingTop: 2,
  },
  sheetCell: {
    backgroundColor: colors.white,
    flex: 1,
    opacity: 0.9,
  },
  settingsIcon: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  settingsRing: {
    borderRadius: 999,
    borderWidth: 2,
    height: "62%",
    position: "absolute",
    width: "62%",
  },
  settingsCore: {
    borderRadius: 999,
    height: "18%",
    position: "absolute",
    width: "18%",
  },
  settingsSpokeHorizontal: {
    borderRadius: 999,
    height: 2,
    position: "absolute",
    width: "92%",
  },
  settingsSpokeVertical: {
    borderRadius: 999,
    height: "92%",
    position: "absolute",
    width: 2,
  },
});
