import { StyleSheet } from "react-native";
import { colors } from "./tokens";

export const styles = StyleSheet.create({
  root: {
    alignItems: "center",
    backgroundColor: colors.background,
    flex: 1,
  },
  phoneFrame: {
    backgroundColor: colors.background,
    flex: 1,
    maxWidth: 430,
    width: "100%",
  },
  topBar: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
  },
  segmentedTabs: {
    backgroundColor: colors.segment,
    borderRadius: 8,
    flexDirection: "row",
    height: 34,
    padding: 4,
    width: 165,
  },
  segmentTab: {
    alignItems: "center",
    borderRadius: 6,
    flex: 1,
    justifyContent: "center",
    minWidth: 0,
  },
  segmentTabActive: {
    backgroundColor: colors.primary,
    shadowColor: "#000000",
    shadowOffset: { height: 1, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 1,
  },
  segmentText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0,
    lineHeight: 18,
  },
  segmentTextActive: {
    color: colors.white,
    fontWeight: "700",
  },
  headerActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "flex-end",
    minWidth: 72,
  },
  mainPanel: {
    backgroundColor: colors.white,
    borderLeftColor: colors.border,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderRightColor: colors.border,
    borderRightWidth: StyleSheet.hairlineWidth,
    flex: 1,
    overflow: "hidden",
  },
  panelScroll: {
    flex: 1,
  },
  chatContent: {
    gap: 12,
    paddingBottom: 32,
    paddingTop: 1,
  },
  dateDivider: {
    alignSelf: "center",
    backgroundColor: colors.datePill,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 4,
  },
  dateDividerText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
    lineHeight: 14,
  },
  selfMessageRow: {
    alignItems: "flex-end",
    paddingLeft: 92,
    width: "100%",
  },
  selfBubble: {
    backgroundColor: colors.primary,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 4,
    borderColor: colors.primaryBorder,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    maxWidth: 298,
    paddingHorizontal: 17,
    paddingVertical: 17,
  },
  selfBubbleText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 20,
  },
  bubbleShadow: {
    elevation: 1,
    shadowColor: "#000000",
    shadowOffset: { height: 1, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 1,
  },
  receiverGroup: {
    alignItems: "flex-start",
    marginLeft: 48,
    maxWidth: 276,
  },
  receiverGroupCompact: {
    alignItems: "flex-start",
    marginLeft: 44,
    marginTop: 16,
    maxWidth: 254,
  },
  senderLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 14,
    marginBottom: 4,
    marginLeft: 8,
  },
  receiverBubble: {
    backgroundColor: colors.received,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 16,
    borderColor: colors.receivedBorder,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 17,
    width: "100%",
  },
  receiverBubbleCompact: {
    maxWidth: 254,
  },
  receiverBubbleText: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 20,
  },
  typingIndicator: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    justifyContent: "center",
    opacity: 0.7,
    paddingTop: 1,
  },
  typingText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 14,
  },
  typingDots: {
    flexDirection: "row",
    gap: 2,
  },
  typingDot: {
    backgroundColor: colors.muted,
    borderRadius: 999,
    height: 4,
    width: 4,
  },
  filesContent: {
    paddingBottom: 32,
  },
  folderRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    minHeight: 49,
    paddingRight: 16,
  },
  fileRowTopBorder: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  folderTitle: {
    color: colors.ink,
    flex: 1,
    fontSize: 16,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 22,
    minWidth: 0,
  },
  folderTitleBold: {
    fontWeight: "700",
  },
  infoIconSlot: {
    marginLeft: "auto",
  },
  fileRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    minHeight: 58,
    paddingRight: 16,
  },
  nestedFileRowTopBorder: {
    borderTopColor: colors.borderSoft,
    borderTopWidth: StyleSheet.hairlineWidth,
    marginLeft: 32,
  },
  fileTextColumn: {
    flex: 1,
    minWidth: 0,
  },
  fileTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 18,
  },
  fileMeta: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 12,
  },
  composer: {
    backgroundColor: colors.surface,
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    gap: 8,
    paddingHorizontal: 20,
    paddingTop: 17,
  },
  toolbarRow: {
    alignItems: "center",
    flexDirection: "row",
    height: 36,
    justifyContent: "space-between",
  },
  toolbarGroup: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  inputRow: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 16,
  },
  inputShell: {
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    height: 58,
    justifyContent: "center",
    paddingHorizontal: 29,
  },
  messageInput: {
    color: colors.ink,
    fontSize: 15,
    height: 42,
    letterSpacing: 0,
    lineHeight: 20,
    padding: 0,
  },
  sendButton: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: 12,
    height: 48,
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    width: 48,
  },
  drawerLayer: {
    backgroundColor: colors.background,
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 20,
  },
  drawerPanel: {
    backgroundColor: colors.white,
    borderRightColor: colors.border,
    borderRightWidth: StyleSheet.hairlineWidth,
    flex: 1,
    width: "100%",
  },
  drawerHeader: {
    alignItems: "center",
    backgroundColor: colors.background,
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
  },
  drawerBrand: {
    color: colors.primary,
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 28,
  },
  drawerSelectors: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  drawerSelectColumn: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  selectLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 15,
  },
  selectBox: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    height: 28,
    justifyContent: "space-between",
    paddingLeft: 9,
    paddingRight: 7,
  },
  selectValue: {
    color: colors.ink,
    flex: 1,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 14,
    minWidth: 0,
  },
  historySection: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
  },
  sectionLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 15,
    marginBottom: 14,
  },
  historyItem: {
    borderRadius: 12,
    paddingHorizontal: 4,
    paddingVertical: 12,
  },
  historyItemPressed: {
    backgroundColor: colors.surface,
  },
  historyTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 24,
  },
  historyPreview: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    lineHeight: 14,
  },
  drawerFooter: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 16,
    paddingTop: 9,
  },
  settingsRow: {
    alignItems: "center",
    borderRadius: 999,
    flexDirection: "row",
    gap: 12,
    minHeight: 48,
    paddingHorizontal: 16,
  },
  settingsText: {
    color: colors.muted,
    fontSize: 16,
    fontWeight: "400",
    letterSpacing: 0,
    lineHeight: 24,
  },
  iconButton: {
    alignItems: "center",
    borderRadius: 999,
    justifyContent: "center",
  },
  pressed: {
    opacity: 0.7,
  },
  iconCanvas: {
    position: "relative",
  },
  iconCenter: {
    alignItems: "center",
    justifyContent: "center",
  },
  iconLine: {
    borderRadius: 999,
    position: "absolute",
  },
  moreDot: {
    borderRadius: 999,
    position: "absolute",
  },
  folderTab: {
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
    position: "absolute",
  },
  folderBody: {
    borderRadius: 2,
    position: "absolute",
  },
  infoIcon: {
    alignItems: "center",
    borderRadius: 999,
    borderWidth: 1.5,
    justifyContent: "center",
  },
  infoIconText: {
    fontWeight: "700",
    includeFontPadding: false,
    lineHeight: 16,
  },
  toolbarImageIcon: {
    borderRadius: 1,
    borderWidth: 1.8,
    position: "relative",
  },
  toolbarImageSun: {
    borderRadius: 999,
    height: 3,
    left: 4,
    position: "absolute",
    top: 4,
    width: 3,
  },
  toolbarImageMountain: {
    borderBottomWidth: 7,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    bottom: 3,
    height: 0,
    position: "absolute",
    right: 3,
    width: 0,
  },
  paperclipOuter: {
    borderRadius: 999,
    borderWidth: 2,
    transform: [{ rotate: "8deg" }],
  },
  paperclipInner: {
    borderRadius: 999,
    borderWidth: 1.6,
    bottom: 3,
    left: 3,
    position: "absolute",
    right: 3,
    top: 5,
  },
  smileFace: {
    borderRadius: 999,
    borderWidth: 1.8,
    position: "relative",
  },
  smileEye: {
    borderRadius: 999,
    height: 3,
    position: "absolute",
    top: 7,
    width: 3,
  },
  smileMouth: {
    borderBottomWidth: 1.8,
    borderRadius: 999,
    bottom: 6,
    height: 5,
    left: 6,
    position: "absolute",
    right: 6,
  },
  micCapsule: {
    borderRadius: 999,
    borderWidth: 1.8,
    position: "absolute",
  },
  micStem: {
    borderRadius: 999,
    position: "absolute",
  },
  micBase: {
    borderRadius: 999,
    position: "absolute",
  },
  circlePlus: {
    alignItems: "center",
    borderRadius: 999,
    borderWidth: 1.8,
    justifyContent: "center",
  },
  fileImageIcon: {
    backgroundColor: colors.purple,
    borderRadius: 2,
    position: "relative",
  },
  fileImageDot: {
    backgroundColor: colors.white,
    borderRadius: 999,
    height: 3,
    left: 3,
    position: "absolute",
    top: 3,
    width: 3,
  },
  fileImageHill: {
    borderBottomColor: colors.white,
    borderBottomWidth: 6,
    borderLeftColor: "transparent",
    borderLeftWidth: 5,
    borderRightColor: "transparent",
    borderRightWidth: 5,
    bottom: 3,
    height: 0,
    position: "absolute",
    right: 2,
    width: 0,
  },
  filePdfIcon: {
    backgroundColor: colors.red,
    borderRadius: 2,
    position: "relative",
  },
  fileFold: {
    borderLeftColor: "transparent",
    borderLeftWidth: 5,
    borderTopColor: colors.white,
    borderTopWidth: 5,
    height: 0,
    position: "absolute",
    right: 0,
    top: 0,
    width: 0,
  },
  filePdfLine: {
    backgroundColor: colors.white,
    borderRadius: 999,
    height: 2,
    left: 3,
    position: "absolute",
    right: 3,
    top: 9,
  },
  filePdfLineShort: {
    right: 7,
    top: 13,
  },
  fileSheetIcon: {
    borderRadius: 2,
    overflow: "hidden",
  },
  fileSheetHeader: {
    backgroundColor: colors.brown,
    height: 5,
  },
  sheetCells: {
    backgroundColor: colors.brown,
    flex: 1,
    flexDirection: "row",
    gap: 2,
    paddingHorizontal: 2,
    paddingTop: 2,
  },
  sheetCell: {
    backgroundColor: colors.white,
    flex: 1,
    opacity: 0.9,
  },
  settingsIcon: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  settingsRing: {
    borderRadius: 999,
    borderWidth: 2,
    height: "62%",
    position: "absolute",
    width: "62%",
  },
  settingsCore: {
    borderRadius: 999,
    height: "18%",
    position: "absolute",
    width: "18%",
  },
  settingsSpokeHorizontal: {
    borderRadius: 999,
    height: 2,
    position: "absolute",
    width: "92%",
  },
  settingsSpokeVertical: {
    borderRadius: 999,
    height: "92%",
    position: "absolute",
    width: 2,
  },
});
