<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <IsTestProject>true</IsTestProject>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);MAAI001;CS1591;NU1507</NoWarn>

    <!-- sync using .editorconfig-->
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)TestTimeProvider.cs" Link="TestTimeProvider.cs" />
  </ItemGroup>
</Project>
