<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="ClaudeCodeSdk.MAF" />
	  <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
	</ItemGroup>


	<ItemGroup>
    <!--<ProjectReference Include="..\..\..\..\claude-code-sdk-csharp\src\ClaudeCodeSdk.MAF\ClaudeCodeSdk.MAF.csproj" />-->
    <ProjectReference Include="..\DSystem.SessionRecords\DSystem.SessionRecords.csproj" />
    <ProjectReference Include="..\DSystem.Shared\DSystem.Shared.csproj" />
  </ItemGroup>

</Project>
