<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<ProjectReference Include="..\DSystem.Agents\DSystem.Agents.csproj" />
		<ProjectReference Include="..\DSystem.Providers\DSystem.Providers.csproj" />
		<ProjectReference Include="..\DSystem.Tasks\DSystem.Tasks.csproj" />
	</ItemGroup>

</Project>
