<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PiAgentSdk.MAF</RootNamespace>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../PiAgentSdk/PiAgentSdk.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
