// <auto-generated />
using System;
using System.Collections.Generic;
using Agw.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agw.Infrastructure.Migrations
{
    [DbContext(typeof(AgwDbContext))]
    [Migration("20260713085347_AddAgentEnvironmentVariables")]
    partial class AddAgentEnvironmentVariables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Agw.Jobs.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<int?>("AgentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_type");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxRetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_retry_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("NextRunTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_run_time");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Prompt")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("TriggerType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trigger_type");

                    b.Property<string>("TriggerValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_value");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_job");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_task_project");

                    b.HasIndex("IsEnabled", "Status", "NextRunTime")
                        .HasDatabaseName("ix_task_next_run_time");

                    b.ToTable("job", (string)null);
                });

            modelBuilder.Entity("Agw.Jobs.Domain.Entities.JobLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_job_log");

                    b.HasIndex("JobId", "StartTime")
                        .HasDatabaseName("ix_job_log_job_id_start_time");

                    b.ToTable("job_log", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("EnvironmentVariables")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("environment_variables");

                    b.Property<string>("Extra")
                        .HasColumnType("TEXT")
                        .HasColumnName("extra");

                    b.Property<Guid?>("ModelProviderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_provider_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("system_prompt");

                    b.Property<string>("Tools")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("tools");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_agent");

                    b.HasIndex("ModelProviderId")
                        .HasDatabaseName("ix_agent_model_provider_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_name");

                    b.ToTable("agent", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.AgentAppRelation", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("AppInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_instance_id");

                    b.HasKey("AgentId", "AppInstanceId")
                        .HasName("pk_agent_app_relation");

                    b.HasIndex("AppInstanceId")
                        .HasDatabaseName("ix_agent_app_relation_app_instance_id");

                    b.ToTable("agent_app_relation", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.AgentMcpServerRelation", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("McpToolServerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("mcp_tool_server_id");

                    b.HasKey("AgentId", "McpToolServerId")
                        .HasName("pk_agent_mcp_server_relation");

                    b.HasIndex("McpToolServerId")
                        .HasDatabaseName("ix_agent_mcp_server_relation_mcp_tool_server_id");

                    b.ToTable("agent_mcp_server_relation", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.AgentSkillRelation", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("TEXT")
                        .HasColumnName("skill_id");

                    b.HasKey("AgentId", "SkillId")
                        .HasName("pk_agent_skill_relation");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_agent_skill_relation_skill_id");

                    b.ToTable("agent_skill_relation", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.Agentflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("system_prompt");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_agentflow");

                    b.ToTable("agentflow", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.AgentflowEdge", b =>
                {
                    b.Property<Guid>("AgentflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agentflow_id");

                    b.Property<string>("EdgeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("edge_id");

                    b.Property<string>("ConditionJson")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("condition_json");

                    b.Property<string>("ConfigJson")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT")
                        .HasColumnName("config_json");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("SourceNodeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_node_id");

                    b.Property<string>("TargetNodeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_node_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("AgentflowId", "EdgeId")
                        .HasName("pk_agentflow_edge");

                    b.HasIndex("AgentflowId", "SourceNodeId")
                        .HasDatabaseName("ix_agentflow_edge_agentflow_id_source_node_id");

                    b.HasIndex("AgentflowId", "TargetNodeId")
                        .HasDatabaseName("ix_agentflow_edge_agentflow_id_target_node_id");

                    b.ToTable("agentflow_edge", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.AgentflowNode", b =>
                {
                    b.Property<Guid>("AgentflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agentflow_id");

                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id");

                    b.Property<string>("ConfigJson")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT")
                        .HasColumnName("config_json");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Instructions")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT")
                        .HasColumnName("instructions");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PositionJson")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("position_json");

                    b.Property<Guid?>("RelateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("relate_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("AgentflowId", "NodeId")
                        .HasName("pk_agentflow_node");

                    b.HasIndex("AgentflowId", "Kind", "RelateId")
                        .HasDatabaseName("ix_agentflow_node_agentflow_id_kind_relate_id");

                    b.ToTable("agentflow_node", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.AgentflowTrace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_name");

                    b.Property<Guid>("AgentflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agentflow_id");

                    b.Property<string>("ContextId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("context_id");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_milliseconds");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id");

                    b.Property<string>("NodeKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("node_kind");

                    b.Property<string>("NodeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("node_name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time_utc");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_agentflow_trace");

                    b.HasIndex("AgentflowId", "NodeId", "StartTimeUtc")
                        .HasDatabaseName("ix_agentflow_trace_agentflow_id_node_id_start_time_utc");

                    b.HasIndex("ProjectId", "ContextId", "TaskId", "StartTimeUtc")
                        .HasDatabaseName("ix_agentflow_trace_project_id_context_id_task_id_start_time_utc");

                    b.ToTable("agentflow_trace", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.McpServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("arguments");

                    b.Property<string>("Command")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("command");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("EnvironmentVariables")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("environment_variables");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("headers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("transport_type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("working_directory");

                    b.HasKey("Id")
                        .HasName("pk_mcp_server");

                    b.ToTable("mcp_server", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Integrations.AppInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("app_name");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_secret");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.Property<bool>("UsePkce")
                        .HasColumnType("INTEGER")
                        .HasColumnName("use_pkce");

                    b.HasKey("Id")
                        .HasName("pk_app_instance");

                    b.HasIndex("AppName")
                        .HasDatabaseName("ix_app_instance_app_name");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_instance_client_id");

                    b.ToTable("app_instance", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Integrations.OAuthAuthorizationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("access_token");

                    b.Property<Guid>("AppInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_instance_id");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_type");

                    b.HasKey("Id")
                        .HasName("pk_oauth_authorization");

                    b.HasIndex("AppInstanceId")
                        .IsUnique()
                        .HasDatabaseName("ix_oauth_authorization_app_instance_id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_oauth_authorization_expires_at_utc");

                    b.ToTable("oauth_authorization", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Providers.LlmModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_tokens");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_model");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_model_name");

                    b.ToTable("model", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Providers.ModelProviderRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("CacheRead")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cache_read");

                    b.Property<decimal>("CacheWrite")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cache_write");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<decimal>("InputPrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("input_price");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_id");

                    b.Property<decimal>("OutputPrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("output_price");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<int>("RpsLimit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rps_limit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_model_provider_relation");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_model_provider_relation_model_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_model_provider_relation_provider_id");

                    b.ToTable("model_provider_relation", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Providers.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("ProviderType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_provider");

                    b.HasIndex("Name", "ProviderType")
                        .IsUnique()
                        .HasDatabaseName("ix_provider_name_provider_type");

                    b.ToTable("provider", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Providers.ProviderAuthConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key");

                    b.Property<int>("AuthType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auth_type");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable");

                    b.Property<string>("EnvName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("env_name");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_provider_auth_config");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_provider_auth_config_provider_id");

                    b.ToTable("provider_auth_config", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Skills.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContentPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_path");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_skill");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_name");

                    b.ToTable("skill", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Tasks.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable");

                    b.Property<string>("ExtraSetting")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT")
                        .HasColumnName("extra_setting");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.Property<string>("Workspace")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_project_name");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Tasks.ProjectContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContextId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("context_id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Untitled")
                        .HasColumnName("title");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Usage", "Agw.Shared.Data.Entities.Tasks.ProjectContext.Usage#ProjectContextUsage", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("CachedInputTokenCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0L)
                                .HasColumnName("usage_cached_input_token_count");

                            b1.Property<long>("InputTokenCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0L)
                                .HasColumnName("usage_input_token_count");

                            b1.Property<long>("OutputTokenCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0L)
                                .HasColumnName("usage_output_token_count");

                            b1.Property<long>("ReasoningTokenCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0L)
                                .HasColumnName("usage_reasoning_token_count");

                            b1.Property<long>("TotalTokenCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0L)
                                .HasColumnName("usage_total_token_count");
                        });

                    b.HasKey("Id")
                        .HasName("pk_project_context");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_project_context_job_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_context_project_id");

                    b.HasIndex("UpdateTime")
                        .HasDatabaseName("ix_project_context_update_time");

                    b.HasIndex("ProjectId", "ContextId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_context_project_id_context_id");

                    b.ToTable("project_context", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Tasks.TaskRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_name");

                    b.Property<string>("ConversationPayload")
                        .HasColumnType("text")
                        .HasColumnName("conversation_payload");

                    b.Property<long?>("ConversationSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("conversation_sequence");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FinishedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_time");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("ProjectContextId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_context_id");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("TaskErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("task_error_message");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_project_task_record");

                    b.HasIndex("ProjectContextId")
                        .HasDatabaseName("ix_project_task_record_project_context_id");

                    b.HasIndex("ProjectContextId", "ConversationSequence")
                        .HasDatabaseName("ix_project_task_record_project_context_id_conversation_sequence");

                    b.HasIndex("TaskId", "ConversationSequence")
                        .HasDatabaseName("ix_project_task_record_task_id_conversation_sequence");

                    b.HasIndex("TaskId", "CreateTime")
                        .HasDatabaseName("ix_project_task_record_task_id_create_time");

                    b.ToTable("project_task_record", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Tasks.TaskSessionBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("ExternalAgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("external_agent_name");

                    b.Property<Guid>("ProjectContextId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_context_id");

                    b.Property<string>("ProviderSessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_session_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_task_session_binding");

                    b.HasIndex("ExternalAgentName", "ProviderSessionId")
                        .HasDatabaseName("ix_task_session_binding_external_agent_name_provider_session_id");

                    b.HasIndex("ProjectContextId", "AgentId", "ExternalAgentName")
                        .IsUnique()
                        .HasDatabaseName("ix_task_session_binding_project_context_id_agent_id_external_agent_name");

                    b.ToTable("task_session_binding", (string)null);
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.Agent", b =>
                {
                    b.HasOne("Agw.Shared.Data.Entities.Providers.ModelProviderRelation", "ModelProvider")
                        .WithMany()
                        .HasForeignKey("ModelProviderId")
                        .HasConstraintName("fk_agent_model_provider_relation_model_provider_id");

                    b.Navigation("ModelProvider");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.AgentAppRelation", b =>
                {
                    b.HasOne("Agw.Shared.Data.Entities.Agents.Agent", "Agent")
                        .WithMany("AgentAppRelations")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_app_relation_agent_agent_id");

                    b.HasOne("Agw.Shared.Data.Entities.Integrations.AppInstance", "AppInstance")
                        .WithMany()
                        .HasForeignKey("AppInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_app_relation_app_instance_app_instance_id");

                    b.Navigation("Agent");

                    b.Navigation("AppInstance");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.AgentMcpServerRelation", b =>
                {
                    b.HasOne("Agw.Shared.Data.Entities.Agents.Agent", "Agent")
                        .WithMany("AgentMcpToolServers")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_mcp_server_relation_agent_agent_id");

                    b.HasOne("Agw.Shared.Data.Entities.Agents.McpServer", "McpToolServer")
                        .WithMany("AgentMcpToolServers")
                        .HasForeignKey("McpToolServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_mcp_server_relation_mcp_server_mcp_tool_server_id");

                    b.Navigation("Agent");

                    b.Navigation("McpToolServer");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.AgentSkillRelation", b =>
                {
                    b.HasOne("Agw.Shared.Data.Entities.Agents.Agent", "Agent")
                        .WithMany("AgentSkillRelations")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_skill_relation_agent_agent_id");

                    b.HasOne("Agw.Shared.Data.Entities.Skills.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_skill_relation_skill_skill_id");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.AgentflowEdge", b =>
                {
                    b.HasOne("Agw.Shared.Data.Entities.Agents.Agentflow", null)
                        .WithMany("Edges")
                        .HasForeignKey("AgentflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agentflow_edge_agentflow_agentflow_id");

                    b.HasOne("Agw.Shared.Data.Entities.Agents.AgentflowNode", "SourceNode")
                        .WithMany("SourceEdges")
                        .HasForeignKey("AgentflowId", "SourceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agentflow_edge_agentflow_node_agentflow_id_source_node_id");

                    b.HasOne("Agw.Shared.Data.Entities.Agents.AgentflowNode", "TargetNode")
                        .WithMany("TargetEdges")
                        .HasForeignKey("AgentflowId", "TargetNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agentflow_edge_agentflow_node_agentflow_id_target_node_id");

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.AgentflowNode", b =>
                {
                    b.HasOne("Agw.Shared.Data.Entities.Agents.Agentflow", null)
                        .WithMany("Nodes")
                        .HasForeignKey("AgentflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agentflow_node_agentflow_agentflow_id");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Integrations.OAuthAuthorizationToken", b =>
                {
                    b.HasOne("Agw.Shared.Data.Entities.Integrations.AppInstance", null)
                        .WithOne("AuthorizationToken")
                        .HasForeignKey("Agw.Shared.Data.Entities.Integrations.OAuthAuthorizationToken", "AppInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oauth_authorization_app_instance_app_instance_id");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Providers.ModelProviderRelation", b =>
                {
                    b.HasOne("Agw.Shared.Data.Entities.Providers.LlmModel", "Model")
                        .WithMany("Providers")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_provider_relation_model_model_id");

                    b.HasOne("Agw.Shared.Data.Entities.Providers.Provider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_provider_relation_provider_provider_id");

                    b.Navigation("Model");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Providers.ProviderAuthConfig", b =>
                {
                    b.HasOne("Agw.Shared.Data.Entities.Providers.Provider", "Provider")
                        .WithMany("AuthConfigs")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_auth_config_provider_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Tasks.ProjectContext", b =>
                {
                    b.HasOne("Agw.Shared.Data.Entities.Tasks.Project", "Project")
                        .WithMany("Contexts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_context_project_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Tasks.TaskRecord", b =>
                {
                    b.HasOne("Agw.Shared.Data.Entities.Tasks.ProjectContext", "ProjectContext")
                        .WithMany("Records")
                        .HasForeignKey("ProjectContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_task_record_project_context_project_context_id");

                    b.Navigation("ProjectContext");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Tasks.TaskSessionBinding", b =>
                {
                    b.HasOne("Agw.Shared.Data.Entities.Tasks.ProjectContext", "ProjectContext")
                        .WithMany()
                        .HasForeignKey("ProjectContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_session_binding_project_context_project_context_id");

                    b.Navigation("ProjectContext");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.Agent", b =>
                {
                    b.Navigation("AgentAppRelations");

                    b.Navigation("AgentMcpToolServers");

                    b.Navigation("AgentSkillRelations");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.Agentflow", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.AgentflowNode", b =>
                {
                    b.Navigation("SourceEdges");

                    b.Navigation("TargetEdges");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Agents.McpServer", b =>
                {
                    b.Navigation("AgentMcpToolServers");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Integrations.AppInstance", b =>
                {
                    b.Navigation("AuthorizationToken");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Providers.LlmModel", b =>
                {
                    b.Navigation("Providers");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Providers.Provider", b =>
                {
                    b.Navigation("AuthConfigs");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Tasks.Project", b =>
                {
                    b.Navigation("Contexts");
                });

            modelBuilder.Entity("Agw.Shared.Data.Entities.Tasks.ProjectContext", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
