source 'https://rubygems.org'

ruby '>= 2.6.10'

gem 'cocoapods', '1.16.2'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '1.27.0'
gem 'concurrent-ruby', '< 1.3.4'
gem 'ffi', '~> 1.15.5'
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
