packages:
  - web
  - desktop
  - packages/*

overrides:
  "@electron/rebuild": 4.0.2

allowBuilds:
  "@code-inspector/core": true
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  node-pty: false
  sharp: true

nodeLinker: hoisted
hoistingLimits: workspaces
autoInstallPeers: false
resolvePeersFromWorkspaceRoot: false
