<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="A2A" />
		<PackageReference Include="A2A.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\DSystem.Appliaction\DSystem.Appliaction.csproj" />
	</ItemGroup>

</Project>
