using Agw.Integrations.Contracts.Capabilities;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;

namespace Agw.Agents.Execution.Agents.Composition;

/// <summary>
/// Represents the capabilities materialized for one Agent runtime.
/// 表示为一次 Agent 运行时物化得到的 Capability 集合。
/// </summary>
/// <remarks>
/// Carries the composed tools, plugin skills, context providers, loop evaluators,
/// approval rules, and warnings consumed while the final Agent is assembled.
/// 保存最终组装 Agent 时使用的工具、Plugin Skill、Context Provider、Loop Evaluator、
/// 审批规则和警告信息。
/// This composition owns the underlying resource lease and must be disposed with the Agent
/// to release Tool, Tool Block, Connection, and MCP resources.
/// 该组合对象拥有底层资源租约，必须随 Agent 一同释放，以清理 Tool、Tool Block、
/// Connection 和 MCP 创建的资源。
/// </remarks>
public sealed class AgentCapabilityComposition : IAsyncDisposable
{
    private readonly AgentResourceLease _lease;
    private readonly List<AIContextProvider> _contextProviders;
    private readonly List<Func<ToolAutoApprovalRuleContext, ValueTask<bool>>> _autoApprovalRules;
    private readonly HashSet<string> _planModeAllowedToolNames;

    internal AgentCapabilityComposition(
        IReadOnlyList<AITool> tools,
        IReadOnlyList<PluginSkillReference> pluginSkills,
        IReadOnlyList<ConnectionCapabilityWarning> warnings,
        IReadOnlyList<AIContextProvider> contextProviders,
        IReadOnlyList<LoopEvaluator> loopEvaluators,
        IReadOnlyList<Func<ToolAutoApprovalRuleContext, ValueTask<bool>>> autoApprovalRules,
        IReadOnlySet<string> planModeAllowedToolNames,
        IReadOnlyList<string> toolWarnings,
        IReadOnlyDictionary<string, string> toolInvocationWarnings,
        AgentResourceLease lease
    )
    {
        Tools = tools;
        PluginSkills = pluginSkills;
        Warnings = warnings;
        _contextProviders = contextProviders.ToList();
        LoopEvaluators = loopEvaluators;
        _autoApprovalRules = autoApprovalRules.ToList();
        _planModeAllowedToolNames = new HashSet<string>(planModeAllowedToolNames, StringComparer.OrdinalIgnoreCase);
        ToolWarnings = toolWarnings;
        ToolInvocationWarnings = toolInvocationWarnings;
        _lease = lease;
    }

    /// <summary>
    /// Tools already created for ChatOptions; excludes tools generated by providers at runtime.
    /// 已创建、可直接加入 ChatOptions 的 Tool；Provider 在运行时生成的 Tool 不在此列表中。
    /// </summary>
    public IReadOnlyList<AITool> Tools { get; }

    /// <summary>
    /// Skill references supplied by integrations, loaded when creating the Skills Provider.
    /// 集成提供的 Skill 引用，供创建 Skills Provider 时加载使用。
    /// </summary>
    public IReadOnlyList<PluginSkillReference> PluginSkills { get; }

    /// <summary>
    /// Structured warnings collected while preparing integration capabilities, with sources and reasons to help diagnose configuration issues.
    /// 准备集成能力时收集的结构化警告，保留来源和原因，便于定位配置问题。
    /// </summary>
    public IReadOnlyList<ConnectionCapabilityWarning> Warnings { get; }

    /// <summary>
    /// Providers that supply context and dynamic tools to the Agent at runtime, executed in list order.
    /// 运行时向 Agent 提供 Context 和动态 Tool 的 Provider，按列表顺序执行。
    /// </summary>
    public IReadOnlyList<AIContextProvider> ContextProviders => _contextProviders;

    /// <summary>
    /// Rules that decide whether the Agent should continue running; LoopAgent is configured when rules are present.
    /// 判断 Agent 是否需要继续执行的规则；有规则时会配置 LoopAgent。
    /// </summary>
    public IReadOnlyList<LoopEvaluator> LoopEvaluators { get; }

    /// <summary>
    /// Automatic approval rules for tool requests; any rule returning true approves the call, except questions requiring a user response.
    /// Tool 请求审批时使用的自动批准规则；任一规则返回 true 即可批准，必须由用户回答的问题除外。
    /// </summary>
    public IReadOnlyList<Func<ToolAutoApprovalRuleContext, ValueTask<bool>>> AutoApprovalRules => _autoApprovalRules;

    /// <summary>
    /// Case-insensitive set of tool names the current Agent may use in Plan mode.
    /// Controls tool availability, not whether execution requires user approval.
    /// 当前 Agent 在 Plan 模式下允许使用的 Tool 名称集合，比较时忽略大小写。
    /// 此集合控制 Tool 能否使用，不决定执行时是否需要用户审批。
    /// </summary>
    public IReadOnlySet<string> PlanModeAllowedToolNames => _planModeAllowedToolNames;

    /// <summary>
    /// Tool notices sent at the beginning of the Agent response, whether or not the corresponding tool is called.
    /// 放在 Agent 响应开头的 Tool 提示，无论对应 Tool 是否实际被调用都会发送。
    /// </summary>
    public IReadOnlyList<string> ToolWarnings { get; }

    /// <summary>
    /// Notices keyed by tool name, sent only when the corresponding call returns a result, such as a local-search fallback notice.
    /// 按 Tool 名称保存的提示，仅在对应调用返回结果时发送，例如使用本地搜索的降级说明。
    /// </summary>
    public IReadOnlyDictionary<string, string> ToolInvocationWarnings { get; }

    public void AddContextProvider(AIContextProvider provider)
    {
        ArgumentNullException.ThrowIfNull(provider);
        _contextProviders.Add(provider);
    }

    public void AddAutoApprovalRule(Func<ToolAutoApprovalRuleContext, ValueTask<bool>> rule)
    {
        ArgumentNullException.ThrowIfNull(rule);
        _autoApprovalRules.Add(rule);
    }

    public void AddPlanModeAllowedToolName(string toolName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(toolName);
        _planModeAllowedToolNames.Add(toolName);
    }

    public void AddPlanModeAllowedToolNames(IEnumerable<string> toolNames)
    {
        ArgumentNullException.ThrowIfNull(toolNames);
        foreach (var toolName in toolNames)
        {
            AddPlanModeAllowedToolName(toolName);
        }
    }

    public void AddResource(IDisposable resource)
    {
        ArgumentNullException.ThrowIfNull(resource);
        _lease.Add(resource);
    }

    public ValueTask DisposeAsync()
    {
        return _lease.DisposeAsync();
    }
}

internal sealed class AgentResourceLease : IAsyncDisposable
{
    private readonly List<IAsyncDisposable> _resources = [];
    private int _disposed;

    public void Add(IAsyncDisposable resource)
    {
        ObjectDisposedException.ThrowIf(Volatile.Read(ref _disposed) != 0, this);

        _resources.Add(resource);
    }

    public void Add(IDisposable resource)
    {
        ObjectDisposedException.ThrowIf(Volatile.Read(ref _disposed) != 0, this);

        _resources.Add(new DisposableResource(resource));
    }

    public async ValueTask DisposeAsync()
    {
        if (Interlocked.Exchange(ref _disposed, 1) != 0)
        {
            return;
        }

        Exception? failure = null;
        for (var index = _resources.Count - 1; index >= 0; index--)
        {
            try
            {
                await _resources[index].DisposeAsync().ConfigureAwait(false);
            }
            catch (Exception exception)
            {
                failure ??= exception;
            }
        }

        if (failure != null)
        {
            throw failure;
        }
    }

    private sealed class DisposableResource : IAsyncDisposable
    {
        private IDisposable? _resource;

        public DisposableResource(IDisposable resource)
        {
            _resource = resource;
        }

        public ValueTask DisposeAsync()
        {
            Interlocked.Exchange(ref _resource, null)?.Dispose();
            return ValueTask.CompletedTask;
        }
    }
}
