<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <NoWarn>$(NoWarn);MAAI001</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="ClaudeCodeSdk.MAF" />
        <PackageReference Include="CodexSdk.MAF" />
        <PackageReference Include="Microsoft.Agents.AI" />
        <PackageReference Include="Microsoft.Agents.AI.OpenAI" />
        <PackageReference Include="Microsoft.Agents.AI.Anthropic" />
        <PackageReference Include="ModelContextProtocol" />
<!--        <ProjectReference Include="..\..\..\..\codex-sdk-csharp\src\CodexSdk.MAF\CodexSdk.MAF.csproj" />-->
<!--        <ProjectReference Include="..\..\..\..\claude-code-sdk-csharp\src\ClaudeCodeSdk.MAF\ClaudeCodeSdk.MAF.csproj" />-->
        <ProjectReference Include="..\Agw.Integrations\Agw.Integrations.csproj" />
        <ProjectReference Include="..\Agw.Providers\Agw.Providers.csproj" />
        <ProjectReference Include="..\Agw.Shared\Agw.Shared.csproj" />
        <ProjectReference Include="..\Agw.Tools\Agw.Tools.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Definitions\" />
      <Folder Include="Runtime\" />
    </ItemGroup>
</Project>
