<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Remove="Infrastructure\**" />
    <EmbeddedResource Remove="Infrastructure\**" />
    <None Remove="Infrastructure\**" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="ClaudeCodeSdk.MAF" />
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" />
    <PackageReference Include="Microsoft.Agents.AI.Anthropic" />
    <PackageReference Include="ModelContextProtocol" />
    <ProjectReference Include="..\Agw.Providers\Agw.Providers.csproj" />
    <ProjectReference Include="..\Agw.Shared.Contract\Agw.Shared.Contract.csproj" />
    <ProjectReference Include="..\Agw.Shared\Agw.Shared.csproj" />
  </ItemGroup>
</Project>
