<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>$(NoWarn);MAAI001</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CodexSdk.MAF" />
    <PackageReference Include="ClaudeCodeSdk.MAF" />
    <ProjectReference Include="../../sdks/pi-agent-sdk-csharp/src/PiAgentSdk.MAF/PiAgentSdk.MAF.csproj" />
    <!--    <ProjectReference Include="..\..\..\..\claude-code-sdk-csharp\src\ClaudeCodeSdk.MAF\ClaudeCodeSdk.MAF.csproj" />-->
    <!--    <ProjectReference Include="..\..\..\..\codex-sdk-csharp\src\CodexSdk.MAF\CodexSdk.MAF.csproj"/>-->
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="ModelContextProtocol" />
    <ProjectReference Include="..\Agw.Agents.Contracts\Agw.Agents.Contracts.csproj" />
    <ProjectReference Include="..\Agw.Auth\Agw.Auth.csproj" />
    <ProjectReference Include="..\Agw.Data\Agw.Data.csproj" />
    <ProjectReference Include="..\Agw.Integrations.Contracts\Agw.Integrations.Contracts.csproj" />
    <ProjectReference Include="..\Agw.Providers.Contracts\Agw.Providers.Contracts.csproj" />
    <ProjectReference Include="..\Agw.Projects.Contracts\Agw.Projects.Contracts.csproj" />
    <ProjectReference Include="..\Agw.Shared\Agw.Shared.csproj" />
    <ProjectReference Include="..\Agw.Skills.Contracts\Agw.Skills.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Definitions\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Agw.Tools/Agw.Tools.csproj" />
  </ItemGroup>
</Project>
