<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<ProjectReference Include="..\DSystem.Appliaction\DSystem.Appliaction.csproj" />
		<ProjectReference Include="..\DSystem.Infrastructure\DSystem.Infrastructure.csproj" />
	</ItemGroup>

</Project>
