<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <ProjectReference Include="..\Agw.Agents\Agw.Agents.csproj" />
        <ProjectReference Include="..\Agw.Shared\Agw.Shared.csproj" />
    </ItemGroup>
</Project>
