// <auto-generated />
using System;
using DSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSystem.Infrastructure.Migrations
{
    [DbContext(typeof(LlmDbContext))]
    [Migration("20251228093312_AddAgentDescription")]
    partial class AddAgentDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DSystem.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<Guid>("ModelProviderApiKeyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_provider_api_key_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("system_prompt");

                    b.Property<string>("Tools")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("tools");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("ModelProviderApiKeyId")
                        .HasDatabaseName("ix_agents_model_provider_api_key_id");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Agentflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ConfigurationJson")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT")
                        .HasColumnName("configuration_json");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Pattern")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pattern");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("system_prompt");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_agentflow");

                    b.ToTable("agentflow", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.AgentflowEdge", b =>
                {
                    b.Property<Guid>("AgentflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agentflow_id");

                    b.Property<string>("EdgeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("edge_id");

                    b.Property<bool>("Animated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("animated");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("SourceNodeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_node_id");

                    b.Property<string>("TargetNodeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_node_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("AgentflowId", "EdgeId")
                        .HasName("pk_agentflow_edges");

                    b.HasIndex("AgentflowId", "SourceNodeId")
                        .HasDatabaseName("ix_agentflow_edges_agentflow_id_source_node_id");

                    b.HasIndex("AgentflowId", "TargetNodeId")
                        .HasDatabaseName("ix_agentflow_edges_agentflow_id_target_node_id");

                    b.ToTable("agentflow_edges", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.AgentflowNode", b =>
                {
                    b.Property<Guid>("AgentflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agentflow_id");

                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<Guid>("RelateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("relate_id");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("AgentflowId", "NodeId")
                        .HasName("pk_agentflow_nodes");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_agentflow_nodes_agent_id");

                    b.HasIndex("AgentflowId", "Type", "RelateId")
                        .IsUnique()
                        .HasDatabaseName("ix_agentflow_nodes_agentflow_id_type_relate_id");

                    b.ToTable("agentflow_nodes", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.LlmModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_tokens");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_models");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("CacheRead")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cache_read");

                    b.Property<decimal>("CacheWrite")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cache_write");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<decimal>("InputPrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("input_price");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_id");

                    b.Property<decimal>("OutputPrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("output_price");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<int>("RpsLimit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rps_limit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_model_providers");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_model_providers_model_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_model_providers_provider_id");

                    b.ToTable("model_providers", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProviderApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable");

                    b.Property<Guid>("ModelProviderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_provider_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_model_provider_api_keys");

                    b.HasIndex("ModelProviderId")
                        .HasDatabaseName("ix_model_provider_api_keys_model_provider_id");

                    b.ToTable("model_provider_api_keys", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ProjectLease", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("LockedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_by");

                    b.Property<DateTime>("LockedUntilUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_until_utc");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("ProjectId")
                        .HasName("pk_project_leases");

                    b.HasIndex("LockedUntilUtc")
                        .HasDatabaseName("ix_project_leases_locked_until_utc");

                    b.ToTable("project_leases", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agentflow_id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_time");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("input");

                    b.Property<string>("OutputJson")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT")
                        .HasColumnName("output_json");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("StartedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_time");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_project_tasks");

                    b.HasIndex("ProjectId", "Status", "UpdateTime")
                        .HasDatabaseName("ix_project_tasks_project_id_status_update_time");

                    b.ToTable("project_tasks", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_providers");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Agent", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.ModelProviderApiKey", "ModelProviderApiKey")
                        .WithMany("Agents")
                        .HasForeignKey("ModelProviderApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agents_model_provider_api_keys_model_provider_api_key_id");

                    b.Navigation("ModelProviderApiKey");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.AgentflowEdge", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.Agentflow", null)
                        .WithMany("Edges")
                        .HasForeignKey("AgentflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agentflow_edges_agentflow_agentflow_id");

                    b.HasOne("DSystem.Domain.Entities.AgentflowNode", "SourceNode")
                        .WithMany("SourceEdges")
                        .HasForeignKey("AgentflowId", "SourceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agentflow_edges_agentflow_nodes_agentflow_id_source_node_id");

                    b.HasOne("DSystem.Domain.Entities.AgentflowNode", "TargetNode")
                        .WithMany("TargetEdges")
                        .HasForeignKey("AgentflowId", "TargetNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agentflow_edges_agentflow_nodes_agentflow_id_target_node_id");

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.AgentflowNode", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.Agent", null)
                        .WithMany("Agentflows")
                        .HasForeignKey("AgentId")
                        .HasConstraintName("fk_agentflow_nodes_agents_agent_id");

                    b.HasOne("DSystem.Domain.Entities.Agentflow", null)
                        .WithMany("Nodes")
                        .HasForeignKey("AgentflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agentflow_nodes_agentflow_agentflow_id");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProvider", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.LlmModel", "Model")
                        .WithMany("Providers")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_providers_models_model_id");

                    b.HasOne("DSystem.Domain.Entities.Provider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_providers_providers_provider_id");

                    b.Navigation("Model");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProviderApiKey", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.ModelProvider", "ModelProvider")
                        .WithMany("ApiKeys")
                        .HasForeignKey("ModelProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_provider_api_keys_model_providers_model_provider_id");

                    b.Navigation("ModelProvider");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ProjectLease", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.Project", "Project")
                        .WithOne()
                        .HasForeignKey("DSystem.Domain.Entities.ProjectLease", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_leases_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ProjectTask", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_tasks_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Agentflows");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Agentflow", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.AgentflowNode", b =>
                {
                    b.Navigation("SourceEdges");

                    b.Navigation("TargetEdges");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.LlmModel", b =>
                {
                    b.Navigation("Providers");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProvider", b =>
                {
                    b.Navigation("ApiKeys");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProviderApiKey", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Provider", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
