// <auto-generated />
using System;
using DSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSystem.Infrastructure.Migrations
{
    [DbContext(typeof(LlmDbContext))]
    [Migration("20251214072608_AddWorkflowDomain")]
    partial class AddWorkflowDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DSystem.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelProviderApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelProviderApiKeyId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.LlmModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProvider", b =>
                {
                    b.Property<Guid>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CacheRead")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CacheWrite")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InputPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OutputPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RpsLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ModelId", "ProviderId");

                    b.HasIndex("ProviderId");

                    b.ToTable("ModelProviders");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProviderApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelId", "ProviderId");

                    b.ToTable("ModelProviderApiKeys");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Pattern")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.WorkflowAgent", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowId", "AgentId");

                    b.HasIndex("AgentId");

                    b.HasIndex("WorkflowId", "Order")
                        .IsUnique();

                    b.ToTable("WorkflowAgents");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Agent", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.ModelProviderApiKey", "ModelProviderApiKey")
                        .WithMany("Agents")
                        .HasForeignKey("ModelProviderApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelProviderApiKey");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProvider", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.LlmModel", "Model")
                        .WithMany("Providers")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DSystem.Domain.Entities.Provider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProviderApiKey", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.ModelProvider", "ModelProvider")
                        .WithMany("ApiKeys")
                        .HasForeignKey("ModelId", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelProvider");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.WorkflowAgent", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.Agent", "Agent")
                        .WithMany("Workflows")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DSystem.Domain.Entities.Workflow", "Workflow")
                        .WithMany("Agents")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.LlmModel", b =>
                {
                    b.Navigation("Providers");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProvider", b =>
                {
                    b.Navigation("ApiKeys");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProviderApiKey", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Provider", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Workflow", b =>
                {
                    b.Navigation("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
