// <auto-generated />
using System;
using DSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSystem.Infrastructure.Migrations
{
    [DbContext(typeof(LlmDbContext))]
    [Migration("20260314145259_RefactorRecords")]
    partial class RefactorRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("DSystem.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Extra")
                        .HasColumnType("TEXT")
                        .HasColumnName("extra");

                    b.Property<Guid?>("ModelProviderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_provider_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("system_prompt");

                    b.Property<string>("Tools")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("tools");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("ModelProviderId")
                        .HasDatabaseName("ix_agents_model_provider_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_agents_name");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.AgentMcpToolServer", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("McpToolServerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("mcp_tool_server_id");

                    b.HasKey("AgentId", "McpToolServerId")
                        .HasName("pk_agent_mcp_tool_servers");

                    b.HasIndex("McpToolServerId")
                        .HasDatabaseName("ix_agent_mcp_tool_servers_mcp_tool_server_id");

                    b.ToTable("agent_mcp_tool_servers", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Agentflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ConfigurationJson")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT")
                        .HasColumnName("configuration_json");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Pattern")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pattern");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("system_prompt");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_agentflow");

                    b.ToTable("agentflow", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.AgentflowEdge", b =>
                {
                    b.Property<Guid>("AgentflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agentflow_id");

                    b.Property<string>("EdgeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("edge_id");

                    b.Property<bool>("Animated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("animated");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("SourceNodeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_node_id");

                    b.Property<string>("TargetNodeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_node_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("AgentflowId", "EdgeId")
                        .HasName("pk_agentflow_edges");

                    b.HasIndex("AgentflowId", "SourceNodeId")
                        .HasDatabaseName("ix_agentflow_edges_agentflow_id_source_node_id");

                    b.HasIndex("AgentflowId", "TargetNodeId")
                        .HasDatabaseName("ix_agentflow_edges_agentflow_id_target_node_id");

                    b.ToTable("agentflow_edges", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.AgentflowNode", b =>
                {
                    b.Property<Guid>("AgentflowId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agentflow_id");

                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("node_id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<Guid>("RelateId")
                        .HasColumnType("TEXT")
                        .HasColumnName("relate_id");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("AgentflowId", "NodeId")
                        .HasName("pk_agentflow_nodes");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_agentflow_nodes_agent_id");

                    b.HasIndex("AgentflowId", "Type", "RelateId")
                        .IsUnique()
                        .HasDatabaseName("ix_agentflow_nodes_agentflow_id_type_relate_id");

                    b.ToTable("agentflow_nodes", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.LlmModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_tokens");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_models");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.McpToolServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("arguments");

                    b.Property<string>("Command")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("command");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("EnvironmentVariables")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("environment_variables");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("headers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("transport_type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("working_directory");

                    b.HasKey("Id")
                        .HasName("pk_mcp_tool_servers");

                    b.ToTable("mcp_tool_servers", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("CacheRead")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cache_read");

                    b.Property<decimal>("CacheWrite")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cache_write");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<decimal>("InputPrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("input_price");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_id");

                    b.Property<decimal>("OutputPrice")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("output_price");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<int>("RpsLimit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rps_limit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_model_providers");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_model_providers_model_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_model_providers_provider_id");

                    b.ToTable("model_providers", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable");

                    b.Property<string>("ExtraSetting")
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT")
                        .HasColumnName("extra_setting");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.Property<string>("Workspace")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ProjectLease", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("LockedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_by");

                    b.Property<DateTime>("LockedUntilUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_until_utc");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("ProjectId")
                        .HasName("pk_project_leases");

                    b.HasIndex("LockedUntilUtc")
                        .HasDatabaseName("ix_project_leases_locked_until_utc");

                    b.ToTable("project_leases", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContextId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("context_id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_time");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("SystemPrompt")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("system_prompt");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Untitled")
                        .HasColumnName("title");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_project_tasks");

                    b.HasAlternateKey("ContextId")
                        .HasName("ak_project_tasks_context_id");

                    b.HasIndex("ContextId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_tasks_context_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_tasks_project_id");

                    b.HasIndex("ProjectId", "Status", "UpdateTime")
                        .HasDatabaseName("ix_project_tasks_project_id_status_update_time");

                    b.ToTable("project_tasks", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("endpoint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("ProviderType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_providers");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ProviderAuthConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key");

                    b.Property<int>("AuthType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auth_type");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable");

                    b.Property<string>("EnvName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("env_name");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_provider_auth_configs");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_provider_auth_configs_provider_id");

                    b.ToTable("provider_auth_configs", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.TaskRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_id");

                    b.Property<int>("AgentType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_type");

                    b.Property<string>("ContextId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("context_id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input");

                    b.Property<string>("Messages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("messages");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id")
                        .HasName("pk_task_records");

                    b.HasIndex("ContextId", "CreateTime")
                        .HasDatabaseName("ix_task_records_context_id_create_time");

                    b.HasIndex("ContextId", "SessionId", "CreateTime")
                        .HasDatabaseName("ix_task_records_context_id_session_id_create_time");

                    b.ToTable("task_records", (string)null);
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Agent", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.ModelProvider", "ModelProvider")
                        .WithMany("Agents")
                        .HasForeignKey("ModelProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_agents_model_providers_model_provider_id");

                    b.Navigation("ModelProvider");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.AgentMcpToolServer", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.Agent", "Agent")
                        .WithMany("AgentMcpToolServers")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_mcp_tool_servers_agents_agent_id");

                    b.HasOne("DSystem.Domain.Entities.McpToolServer", "McpToolServer")
                        .WithMany("AgentMcpToolServers")
                        .HasForeignKey("McpToolServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_mcp_tool_servers_mcp_tool_servers_mcp_tool_server_id");

                    b.Navigation("Agent");

                    b.Navigation("McpToolServer");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.AgentflowEdge", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.Agentflow", null)
                        .WithMany("Edges")
                        .HasForeignKey("AgentflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agentflow_edges_agentflow_agentflow_id");

                    b.HasOne("DSystem.Domain.Entities.AgentflowNode", "SourceNode")
                        .WithMany("SourceEdges")
                        .HasForeignKey("AgentflowId", "SourceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agentflow_edges_agentflow_nodes_agentflow_id_source_node_id");

                    b.HasOne("DSystem.Domain.Entities.AgentflowNode", "TargetNode")
                        .WithMany("TargetEdges")
                        .HasForeignKey("AgentflowId", "TargetNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agentflow_edges_agentflow_nodes_agentflow_id_target_node_id");

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.AgentflowNode", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.Agent", null)
                        .WithMany("Agentflows")
                        .HasForeignKey("AgentId")
                        .HasConstraintName("fk_agentflow_nodes_agents_agent_id");

                    b.HasOne("DSystem.Domain.Entities.Agentflow", null)
                        .WithMany("Nodes")
                        .HasForeignKey("AgentflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agentflow_nodes_agentflow_agentflow_id");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProvider", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.LlmModel", "Model")
                        .WithMany("Providers")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_providers_models_model_id");

                    b.HasOne("DSystem.Domain.Entities.Provider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_providers_providers_provider_id");

                    b.Navigation("Model");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ProjectLease", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.Project", "Project")
                        .WithOne()
                        .HasForeignKey("DSystem.Domain.Entities.ProjectLease", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_leases_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ProviderAuthConfig", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.Provider", "Provider")
                        .WithMany("AuthConfigs")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_auth_configs_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.TaskRecord", b =>
                {
                    b.HasOne("DSystem.Domain.Entities.ProjectTask", null)
                        .WithMany("ConversationList")
                        .HasForeignKey("ContextId")
                        .HasPrincipalKey("ContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_records_project_tasks_context_id");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Agent", b =>
                {
                    b.Navigation("AgentMcpToolServers");

                    b.Navigation("Agentflows");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Agentflow", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.AgentflowNode", b =>
                {
                    b.Navigation("SourceEdges");

                    b.Navigation("TargetEdges");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.LlmModel", b =>
                {
                    b.Navigation("Providers");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.McpToolServer", b =>
                {
                    b.Navigation("AgentMcpToolServers");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ModelProvider", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.ProjectTask", b =>
                {
                    b.Navigation("ConversationList");
                });

            modelBuilder.Entity("DSystem.Domain.Entities.Provider", b =>
                {
                    b.Navigation("AuthConfigs");

                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
