<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <ProjectReference Include="..\Agw.Files\Agw.Files.csproj" />
    <ProjectReference Include="..\Agw.Shared\Agw.Shared.csproj" />
  </ItemGroup>
</Project>
