using Xunit;

namespace Agw.Architecture.Tests;

public sealed partial class BackendArchitectureTests
{
    [Theory]
    [InlineData("DbContext context;", 1, 0)]
    [InlineData("Agw.Infrastructure.Data.AgwDbContext context;", 1, 0)]
    [InlineData("IRepository<Agent> repository;", 0, 1)]
    [InlineData("services.GetRequiredService<DbContext>();", 1, 0)]
    [InlineData("services.GetRequiredService<AgwDbContext>();", 1, 0)]
    [InlineData("class Wrapper { public DbContext Context => services.GetRequiredService<DbContext>(); }", 2, 0)]
    [InlineData("IAgentsDbContext context; context.Agents.ToListAsync();", 0, 0)]
    public void RawPersistenceInventory_CountsConcreteDependencies(string source, int contexts, int repositories)
    {
        // Arrange / Act
        var actual = CountRawPersistenceAccess(source);

        // Assert
        Assert.Equal((contexts, repositories), actual);
    }

    [Theory]
    [InlineData("using Context = Microsoft.EntityFrameworkCore.DbContext; services.GetRequiredService<Context>();")]
    [InlineData("global using Context = Agw.Infrastructure.Data.AgwDbContext; Context context;")]
    [InlineData("using Repo = Agw.Shared.Data.Repositories.IRepository<Agent>; Repo repository;")]
    public void RawPersistenceInventory_AliasesCannotHideDependencies(string source)
    {
        // Arrange
        var sources = new Dictionary<string, string> { ["Agw.Agents/Store.cs"] = source };
        var baseline = new Dictionary<string, (int, int)>
        {
            ["Agw.Agents/Store.cs"] = CountRawPersistenceAccess(source),
        };

        // Act
        var violations = FindRawPersistenceViolations(sources, baseline);

        // Assert
        Assert.Contains(violations, violation => violation.Contains("alias", StringComparison.Ordinal));
    }

    [Theory]
    [InlineData("Agw.Agents/NewStore.cs", "DbContext context;")]
    [InlineData("Agw.Agents/Store.cs", "DbContext first; DbContext second;")]
    [InlineData("Agw.Agents/Store.cs", "IAgentsDbContext context;")]
    [InlineData("Agw.Agents/Store.cs", "IRepository<Agent> repository;")]
    public void RawPersistenceInventory_NewMovedReducedOrChangedAccessRequiresExactUpdate(string path, string source)
    {
        // Arrange
        var sources = new Dictionary<string, string> { [path] = source };
        var baseline = new Dictionary<string, (int, int)> { ["Agw.Agents/Store.cs"] = (1, 0) };

        // Act
        var violations = FindRawPersistenceViolations(sources, baseline);

        // Assert
        Assert.NotEmpty(violations);
    }

    [Theory]
    [InlineData("Agw.Agents/bin/Store.cs", "DbContext context;")]
    [InlineData("Agw.Agents/obj/Store.cs", "DbContext context;")]
    [InlineData("Agw.Agents/Store.g.cs", "DbContext context;")]
    [InlineData("Agw.Agents/Store.g.i.cs", "DbContext context;")]
    [InlineData("Agw.Agents/Store.generated.cs", "DbContext context;")]
    [InlineData("Agw.Agents/Store.cs", "// <auto-generated />\nDbContext context;")]
    public void RawPersistenceInventory_GeneratedAndBuildOutputIsExcluded(string path, string source)
    {
        // Arrange
        var sources = new Dictionary<string, string> { [path] = source };

        // Act
        var violations = FindRawPersistenceViolations(sources, new Dictionary<string, (int, int)>());

        // Assert
        Assert.Empty(violations);
    }
}
